language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm run lint
- npm test
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: nfve0PfeikyNWF/wutBGc8KsXeEqMbGF/q6aQ/0OPZKOPa7LGPn0AzONt5GXPN4YqeP1emTamcqbz7ZSYXc7H6IzJU3aGCy1wxtHBuVvb95NyKrvI+v2ELy9FNoOzCfjw4VuZsRcRMHNIxunW7jpU0f7TdvxeWXyRDwkBCIuHK7odP7KvcveTlOvNlGOdBK2kMcP2V4IJzyoGZ21FmFo6stG1wn/quiyfDZes4zVaH70XaSefGT2b1BQu7d43ECe7Jg90HwxBpxHc0I9cEfxbyvPnfnrWdOKkQiGGGnyIAi2mTpU8K8jUJWoyiMLogPIb8jHz5LNw066uiTxPk18ass4Y/+j7D9fX6T3npo3wxqhWibXP8qaSU0bJimGrUmZ3IWoQ+r/vehfgpkfbRJqR3n12uNf0Oqr/uWl++//wyAy+oL3acFyqw2KqfF90oMuFA1tTe1UJL26h3EfwNosNuHsc6GA1H3mDe8XiLeWDDHj+flnIoD5XOsFU9oAuaHlAHjVLGBNJtXna3th82RNSgZq5fO7LjmbzXd6yiTjQKpDGXF6ib4rbU1KH37CQ6dOXOGMgnl02VMjT/YMVHz9LvpHiTlXTmT+144MHx7QMf7rQHmbAhrdPyvdDEJMh2UnfZNzKLcVr3Pd6PtbKucFIlQYZLBwnUE62kjgX8rxKro=
  app: macros-calculator

